version: '3'
services:
  devcontainer:
    build: .
    container_name: devcontainer
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ..:/workspace:cached
